name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk wget autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        python -m pip install --upgrade pip
        pip install --upgrade buildozer cython==0.29.33 virtualenv

    - name: Build APK with Buildozer
      run: |
        yes | buildozer android debug
      continue-on-error: false

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: bahnschranken-tracker-apk
        path: bin/*.apk
